library(readr)
library(caret)
library(ggplot2)
library(randomForest)
iris_data <- read_csv("IRIS.csv")
head(iris_data)
iris_data$species <- as.factor(iris_data$species)
set.seed(123)
train_index <- createDataPartition(iris_data$species, p = 0.8, list = FALSE)
train_data <- iris_data[train_index, ]
test_data <- iris_data[-train_index, ]
model <- train(species ~ ., data = train_data, method = 'rf', trControl = trainControl(method = 'cv', number = 10))
print(model)
predictions <- predict(model, test_data)
confusion_matrix <- confusionMatrix(predictions, test_data$species)
print(confusion_matrix)
importance <- varImp(model)
plot(importance)
saveRDS(model, 'iris_rf_model.rds')
