install.packages("caret")
library(caret)
library(tidyverse)
install.packages("randomForest")
library(randomForest)
titanic<-read.csv("Titanic-Dataset.csv")
head(titanic)
summary(titanic)
str(titanic)
titanic$Age[is.na(titanic$Age)] <- median(titanic$Age, na.rm = TRUE)
titanic$Embarked[is.na(titanic$Embarked)] <- 'S'
titanic <- titanic %>% select(-Cabin)
titanic$Survived <- as.factor(titanic$Survived)
titanic$Pclass <- as.factor(titanic$Pclass)
titanic$Sex <- as.factor(titanic$Sex)
titanic$Embarked <- as.factor(titanic$Embarked)
titanic <- titanic %>% mutate(FamilySize = SibSp + Parch)
set.seed(123)
trainIndex <- createDataPartition(titanic$Survived, p = 0.8, list = FALSE)
trainData <- titanic[trainIndex,]
testData <- titanic[-trainIndex,]
set.seed(123)
model <- randomForest(Survived ~ Pclass + Sex + Age + Fare + Embarked + FamilySize, data = trainData)
print(model)
predictions <- predict(model, testData)
print(predictions)
confusionMatrix(predictions, testData$Survived)
